# The manifest for the "pipeline-eduverse-api-eduverse@aws-eduverse" pipeline.
# This YAML file defines your pipeline: the source repository it tracks and the order of the environments to deploy to.
# For more info: https://aws.github.io/copilot-cli/docs/manifest/pipeline/

# The name of the pipeline.
### Change the 'name' due to ValidationError
### name: pipeline-eduverse-api-eduverse@aws-eduverse
### check if pipeline exists: describe stack pipeline-eduverse-api-eduverse@aws-eduverse: ValidationError: 1 validation error detected: Value 'pipeline-eduverse-api-eduverse@aws-eduverse' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*|arn:[-a-zA-Z0-9:/._+]*
name: pipeline-eduverse-api-eduverse

# The version of the schema used in this template.
version: 1

# This section defines your source, changes to which trigger your pipeline.
source:
  # The name of the provider that is used to store the source artifacts.
  # (i.e. GitHub, Bitbucket, CodeCommit)
  provider: CodeCommit
  # Additional properties that further specify the location of the artifacts.
  properties:
    branch: main
    ###  Remove 'eduverse@', due to repository lookup problem.
    ###  repository: https://ap-northeast-2.console.aws.amazon.com/codesuite/codecommit/repositories/eduverse@aws-eduverse/browse
    repository: https://ap-northeast-2.console.aws.amazon.com/codesuite/codecommit/repositories/aws-eduverse/browse

# This section defines the order of the environments your pipeline will deploy to.
stages:
    - # The name of the environment.
      name: dev
      # Optional: flag for manual approval action before deployment.
      # requires_approval: true
      # Optional: use test commands to validate this stage of your build.
      # test_commands: [echo 'running tests', make test]

